# -*- coding: utf-8 -*-
"""Stamp an already-rendered PDF: watermark, guilloche, microtext, QR block.

Sealing is deliberately a *post-process*, not something the report template
does. Three things follow from that, and they are the reason the module is
shaped this way:

- No report template is ever touched. The operation letters render exactly as
  they always did, and a document that was never generated by us — a scanned
  attestation dropped in the folder — can be sealed the same way.
- Re-stamping (a different marking, a new validity) costs a stamp pass, not a
  re-render. The source PDF is kept, so the seal is always applied to clean
  bytes rather than on top of an older seal.
- Redaction for the portal's confirm-only mode is real: ``redact()`` removes
  the text from the content stream instead of drawing a box over it.

Everything here is pure: bytes in, bytes out, no ORM. The caller owns storage.

The one thing a post-process cannot do is reflow the page, and the documents
we seal leave no room for a stamp block — the LoI's paperformat keeps a 5 mm
top and 10 mm bottom margin, and the crew table grows into whatever is left.
``SealSpec.band`` is how that is resolved; see BAND_MODES below.
"""

import hashlib
import io
import math

try:  # PyMuPDF renamed its import in 1.24; the stack still ships both names.
    import pymupdf
except ImportError:  # pragma: no cover - older wheels
    import fitz as pymupdf

import qrcode

# ---------------------------------------------------------------------------
# Geometry. PDF user space: 1 pt = 1/72 in, origin top-left in PyMuPDF.
# ---------------------------------------------------------------------------
MM = 72.0 / 25.4

# Height reserved for the seal block when the page has to make room for it.
# Sized so the shrink it forces on an A4 page stays around 8%: any deeper and
# the letter starts to read as a reduced photocopy of itself.
SEAL_BAND_H = 24 * MM
SEAL_QR_SIDE = 18 * MM
SEAL_QR_GAP = 3 * MM
SEAL_TEXT_W = 62 * MM
# Clearance kept between the seal block and anything the document already
# prints, when deciding whether the corner is free.
SEAL_CLEARANCE = 5.0

# The guilloche frame: two rules inset from the trim, with the engraved line
# running between them. Kept inside 5 mm so it never reaches the text area of
# a report whose top margin is itself only 5 mm.
FRAME_OUTER = 8.0
FRAME_INNER = 12.0

MICROTEXT_SIZE = 1.0
MICROTEXT_FROM_BOTTOM = 9.0

# Black, not grey. A redaction should read as a deliberate act at a glance —
# grey invites the reader to wonder whether the page simply printed badly.
REDACTION_FILL = (0.0, 0.0, 0.0)

BAND_MODES = (
    # Look at where the document's content actually ends on its last page: if
    # the seal's corner is clear, stamp it on at full size; if something is
    # already there, fall back to 'scale' for that document only. A two-crew
    # letter keeps its exact scale, a twenty-three-crew one gives up 8%.
    'auto',
    # Shrink the page content into the area above a reserved band, then stamp
    # the seal into that band. The page stays exactly A4 and nothing can ever
    # be covered, at the cost of a few per cent of scale.
    'scale',
    # Draw the seal straight onto the corner of the page as it is. Nothing is
    # scaled; whatever the document already had in that corner is under it.
    'overlay',
)


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------
def fingerprint(pdf_bytes):
    """SHA-256 of *pdf_bytes*, lowercase hex.

    Note for callers: a file cannot carry its own fingerprint, so what gets
    printed on the page is the fingerprint of the PDF *before* sealing. The
    sealed file's own hash is computed afterwards and only ever shown on the
    verification page.
    """
    return hashlib.sha256(pdf_bytes or b'').hexdigest()


def rgb(value, default=(0.06, 0.19, 0.31)):
    """'#10314F' -> (0.06, 0.19, 0.31). PyMuPDF wants floats in 0..1."""
    if not value:
        return default
    text = value.strip().lstrip('#')
    if len(text) != 6:
        return default
    try:
        return tuple(int(text[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    except ValueError:
        return default


def qr_png(url, box_size=10, border=1):
    """QR for *url* as PNG bytes.

    Error correction M: enough to survive a stamp, a fold and a fax, without
    inflating the module count to the point where the printed square stops
    scanning at 20 mm.
    """
    code = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=box_size,
        border=border,
    )
    code.add_data(url)
    code.make(fit=True)
    buffer = io.BytesIO()
    code.make_image(fill_color='black', back_color='white').save(buffer, format='PNG')
    return buffer.getvalue()


class SealSpec:
    """Everything the stamp needs, resolved by the caller.

    Kept as a plain object rather than a dict so a typo raises here instead of
    silently dropping a layer off the page.
    """

    def __init__(
        self, reference, verify_url, source_hash, company_name='',
        watermark_text='', watermark_opacity=9, watermark_angle=-32,
        watermark_size=24, watermark_mode='tile', watermark_color='#10314F',
        guilloche=True, microtext=True, qr_corner='br', band='auto',
    ):
        self.reference = reference or ''
        self.verify_url = verify_url or ''
        self.source_hash = source_hash or ''
        self.company_name = company_name or ''
        self.watermark_text = watermark_text or ''
        self.watermark_opacity = max(0, min(100, int(watermark_opacity or 0)))
        self.watermark_angle = int(watermark_angle or 0)
        self.watermark_size = max(6, int(watermark_size or 24))
        self.watermark_mode = watermark_mode if watermark_mode in ('tile', 'single') else 'tile'
        self.watermark_color = watermark_color
        self.guilloche = bool(guilloche)
        self.microtext = bool(microtext)
        self.qr_corner = 'bl' if qr_corner == 'bl' else 'br'
        self.band = band if band in BAND_MODES else 'auto'


# ---------------------------------------------------------------------------
# Layers
# ---------------------------------------------------------------------------
def _draw_guilloche(page, color):
    """Two rules around the trim with an engraved wave running between them.

    The wave is confined to the 4 pt channel between the rules rather than
    banded across the head and foot of the page as a security print would do:
    sealing runs on a PDF that is already laid out, and on these reports the
    head of the page is letterhead from edge to edge. A wave there would sit
    on top of the logo box.
    """
    rect = page.rect
    shape = page.new_shape()

    shape.draw_rect(pymupdf.Rect(
        FRAME_OUTER, FRAME_OUTER, rect.width - FRAME_OUTER, rect.height - FRAME_OUTER))
    shape.finish(color=color, width=0.9, stroke_opacity=0.30, fill=None)

    shape.draw_rect(pymupdf.Rect(
        FRAME_INNER, FRAME_INNER, rect.width - FRAME_INNER, rect.height - FRAME_INNER))
    shape.finish(color=(0.61, 0.48, 0.24), width=0.5, stroke_opacity=0.42, fill=None)

    mid = (FRAME_OUTER + FRAME_INNER) / 2.0
    amp = (FRAME_INNER - FRAME_OUTER) / 2.0 - 0.3
    for base, horizontal in (
        (mid, True), (rect.height - mid, True),
        (mid, False), (rect.width - mid, False),
    ):
        span = rect.width if horizontal else rect.height
        for phase_index in range(2):
            phase = phase_index * math.pi
            points = []
            steps = int(span / 3)
            for step in range(steps + 1):
                along = span * step / steps
                offset = math.sin((along / span) * math.pi * 2 * 26 + phase) * amp
                points.append(
                    pymupdf.Point(along, base + offset) if horizontal
                    else pymupdf.Point(base + offset, along)
                )
            shape.draw_polyline(points)
            shape.finish(color=color, width=0.35, stroke_opacity=0.22, fill=None,
                         closePath=False)
    shape.commit(overlay=False)


def _draw_watermark(page, spec):
    """Diagonal marking, tiled or as a single band.

    Every glyph is rotated about the same pivot — the page centre — so the
    whole grid turns as one piece instead of each tile spinning in place.
    """
    text = spec.watermark_text.strip()
    if not text or not spec.watermark_opacity:
        return
    rect = page.rect
    colour = rgb(spec.watermark_color)
    opacity = spec.watermark_opacity / 100.0
    centre = pymupdf.Point(rect.width / 2, rect.height / 2)
    matrix = pymupdf.Matrix(spec.watermark_angle)

    if spec.watermark_mode == 'single':
        size = spec.watermark_size * 1.85
        width = pymupdf.get_text_length(text, fontname='hebo', fontsize=size)
        page.insert_text(
            pymupdf.Point(centre.x - width / 2, centre.y + size * 0.35), text,
            fontname='hebo', fontsize=size, color=colour,
            fill_opacity=opacity, morph=(centre, matrix), overlay=False,
        )
        return

    # Tile metrics come from the design prototype's SVG pattern, so a marking
    # lands on the page at the density it was drawn at:
    #   width = max(200, len * size * 0.68) + 46, height = size * 4.
    size = spec.watermark_size
    step_x = max(200.0, len(text) * size * 0.68) + 46
    step_y = size * 4.0
    # Rotating about the centre pulls the corners in, so the grid is laid out
    # over the page's diagonal in both directions and clipped by the page.
    reach = math.hypot(rect.width, rect.height) / 2 + max(step_x, step_y)
    rows = int(reach * 2 / step_y) + 1
    cols = int(reach * 2 / step_x) + 1
    for row in range(rows):
        y = centre.y - reach + row * step_y
        for col in range(cols):
            x = centre.x - reach + col * step_x
            page.insert_text(
                pymupdf.Point(x, y), text, fontname='hebo', fontsize=size,
                color=colour, fill_opacity=opacity,
                morph=(centre, matrix), overlay=False,
            )


def _draw_microtext(page, spec):
    """The reference repeated at 1 pt along the foot: a grey rule to the eye,
    legible under a loupe, and a smear once photocopied."""
    if not spec.microtext or not spec.reference:
        return
    rect = page.rect
    unit = ' · '.join(filter(None, [
        spec.reference, (spec.source_hash or '')[:24], spec.company_name.upper(),
    ])) + ' · '
    width = pymupdf.get_text_length(unit, fontname='cour', fontsize=MICROTEXT_SIZE)
    if width <= 0:
        return
    usable = rect.width - 2 * FRAME_INNER - 4
    line = unit * (int(usable / width) + 1)
    page.insert_text(
        pymupdf.Point(FRAME_INNER + 2, rect.height - MICROTEXT_FROM_BOTTOM),
        line, fontname='cour', fontsize=MICROTEXT_SIZE,
        color=(0.35, 0.35, 0.35), fill_opacity=0.85, overlay=True,
    )


def _seal_rect(page_rect, corner, band_top=None):
    """Where the seal block lands. One definition, so the collision test and
    the drawing can never disagree about it."""
    total_w = SEAL_QR_SIDE + SEAL_QR_GAP + SEAL_TEXT_W
    if band_top is not None:
        top = band_top + (SEAL_BAND_H - SEAL_QR_SIDE) / 2
    else:
        top = page_rect.height - FRAME_INNER - 6 - SEAL_QR_SIDE
    if corner == 'bl':
        left = FRAME_INNER + 8
    else:
        left = page_rect.width - FRAME_INNER - 8 - total_w
    return pymupdf.Rect(left, top, left + total_w, top + SEAL_QR_SIDE)


def _corner_is_free(page, corner):
    """True when nothing the document prints reaches into the seal's corner.

    Consulted only in 'auto' band mode. Full-page drawings are ignored: a
    background panel or a border frame covers the corner by definition and
    would otherwise push every document into the scaled branch.
    """
    probe = _seal_rect(page.rect, corner) + (
        -SEAL_CLEARANCE, -SEAL_CLEARANCE, SEAL_CLEARANCE, SEAL_CLEARANCE)
    page_area = page.rect.get_area()

    for block in page.get_text('blocks'):
        if probe.intersects(pymupdf.Rect(*block[:4])):
            return False
    for drawing in page.get_drawings():
        rect = drawing.get('rect')
        if rect and rect.get_area() < page_area * 0.8 and probe.intersects(rect):
            return False
    try:
        for info in page.get_image_info():
            if probe.intersects(pymupdf.Rect(info['bbox'])):
                return False
    except Exception:  # noqa: BLE001 - image info is best effort
        pass
    return True


def _draw_seal_block(page, spec, band_top=None):
    """QR, the verify URL, the reference and the printed fingerprint.

    *band_top* is the top of the reserved band when the page made room for the
    block; None means it is being stamped straight onto a free corner.
    """
    block = _seal_rect(page.rect, spec.qr_corner, band_top)
    left, top = block.x0, block.y0

    page.insert_image(
        pymupdf.Rect(left, top, left + SEAL_QR_SIDE, top + SEAL_QR_SIDE),
        stream=qr_png(spec.verify_url), keep_proportion=True,
    )

    ink = (0.06, 0.19, 0.31)
    text_x = left + SEAL_QR_SIDE + SEAL_QR_GAP
    cursor = top + 5.4
    page.insert_text(pymupdf.Point(text_x, cursor),
                     'SCAN OR TYPE THE REFERENCE TO VERIFY',
                     fontname='hebo', fontsize=5.4, color=ink)
    cursor += 7.4
    # Printed without the scheme, the way the design does it: the QR carries
    # the full URL, and the line under it is there to be retyped, not clicked.
    printed_url = spec.verify_url.split('://', 1)[-1]
    page.insert_text(pymupdf.Point(text_x, cursor), printed_url,
                     fontname='cour', fontsize=5.8, color=(0.35, 0.38, 0.42))
    cursor += 10.5
    page.insert_text(pymupdf.Point(text_x, cursor), spec.reference,
                     fontname='hebo', fontsize=10.5, color=ink)
    if spec.source_hash:
        cursor += 8.0
        page.insert_text(pymupdf.Point(text_x, cursor),
                         'SHA-256 %s' % spec.source_hash[:12],
                         fontname='cour', fontsize=5.6, color=(0.47, 0.50, 0.54))


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------
def _needs_band(src_page, spec):
    """Whether this page has to give up a strip for the seal block."""
    if spec.band == 'scale':
        return True
    if spec.band == 'overlay':
        return False
    return not _corner_is_free(src_page, spec.qr_corner)


def seal(pdf_bytes, spec):
    """Return *pdf_bytes* stamped according to *spec*.

    The watermark, guilloche and microtext go on every page; the seal block is
    printed once, on the last page, which is where a reader looks for a
    signature.
    """
    source = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        out = pymupdf.open()
        try:
            last = source.page_count - 1
            for index in range(source.page_count):
                src_page = source[index]
                src_rect = src_page.rect
                page = out.new_page(width=src_rect.width, height=src_rect.height)
                band_top = None
                if index == last and _needs_band(src_page, spec):
                    band_top = src_rect.height - SEAL_BAND_H
                    target = pymupdf.Rect(0, 0, src_rect.width, band_top)
                else:
                    target = pymupdf.Rect(0, 0, src_rect.width, src_rect.height)
                # show_pdf_page embeds the source as a form XObject: vectors
                # stay vectors and the text stays selectable and searchable.
                page.show_pdf_page(target, source, index)

                if spec.guilloche:
                    _draw_guilloche(page, rgb(spec.watermark_color))
                _draw_watermark(page, spec)
                _draw_microtext(page, spec)
                if index == last:
                    _draw_seal_block(page, spec, band_top)
            return out.tobytes(deflate=True, garbage=3)
        finally:
            out.close()
    finally:
        source.close()


def render_page(pdf_bytes, page_number=0, dpi=110):
    """Rasterise one page to PNG bytes.

    Both the desk preview and the portal's copy of the document go through
    here. Rasterising rather than embedding the PDF is a deliberate choice for
    the public side: a PDF in a viewer carries its own save, print and text
    extraction, all of it outside the gate that decided the reader was allowed
    to see the page at all. A picture has none of that, and the reader's job —
    comparing what is on screen with the paper in their hand — needs nothing
    more.
    """
    document = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        if page_number >= document.page_count:
            return b''
        pixmap = document[page_number].get_pixmap(dpi=dpi)
        return pixmap.tobytes('png')
    finally:
        document.close()


def page_count(pdf_bytes):
    document = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        return document.page_count
    finally:
        document.close()


def locate(pdf_bytes, needles):
    """Where each of *needles* sits in the document.

    Returns ``[{'p': page_index, 'r': [x0, y0, x1, y1]}, ...]`` in the
    document's own coordinates. Measured once against a known document, so a
    later redaction blanks exactly where something was found rather than
    searching the page again for a string that may also appear elsewhere on it.
    """
    wanted = [str(value) for value in (needles or []) if value and str(value).strip()]
    if not wanted:
        return []
    boxes = []
    document = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        for index, page in enumerate(document):
            for needle in wanted:
                for rect in page.search_for(needle):
                    boxes.append({'p': index,
                                  'r': [round(value, 2) for value in rect]})
        return boxes
    finally:
        document.close()


def redact_boxes(pdf_bytes, boxes):
    """Remove whatever sits inside *boxes*.

    A real redaction — ``apply_redactions`` drops the glyphs from the content
    stream, so the text is not merely covered. Images and line art are left
    alone (``images=0, graphics=0``): a crew table's own rules touch the
    rectangles, and removing them would take the grid apart around the blanked
    cells.
    """
    if not boxes:
        return pdf_bytes
    by_page = {}
    for box in boxes:
        by_page.setdefault(box['p'], []).append(box['r'])

    document = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        for index, rects in by_page.items():
            if index >= document.page_count:
                continue
            page = document[index]
            for rect in rects:
                page.add_redact_annot(pymupdf.Rect(*rect), fill=REDACTION_FILL)
            page.apply_redactions(images=0, graphics=0, text=0)
        return document.tobytes(deflate=True, garbage=3)
    finally:
        document.close()


def redact(pdf_bytes, needles):
    """Locate and remove in one step, for callers that hold the values."""
    return redact_boxes(pdf_bytes, locate(pdf_bytes, needles))


def text_tokens(pdf_bytes):
    """Every word in the document, for checking what a redaction left behind."""
    document = pymupdf.open(stream=pdf_bytes, filetype='pdf')
    try:
        return [word[4] for page in document for word in page.get_text('words')]
    finally:
        document.close()
